export const PROGRAMS_SCHEDULE = [
  {
    name: 'D-Lokos',
    slug: 'd-lokos',
    logoPath: '/images/programas/d-lokos.png',
    days: ['L', 'M', 'X', 'J', 'V'],
    startHour: 12,
    endHour: 14,
    isComingSoon: false,
  },
  {
    name: 'Pick and Roll',
    slug: 'pick-and-roll',
    logoPath: '/images/programas/pick-and-roll.png',
    days: ['L', 'V'],
    startHour: 19,
    endHour: 20,
    isComingSoon: false,
  },
  {
    name: 'Segona Jugada',
    slug: 'segona-jugada',
    logoPath: '/images/programas/segona-jugada.png',
    days: ['M'],
    startHour: 19,
    endHour: 20,
    isComingSoon: false,
  },
  {
    name: 'Esto es Futbol Papa',
    slug: 'esto-es-futbol-papa',
    logoPath: '/images/programas/esto-es-futbol-papa.png',
    days: ['M'],
    startHour: 14,
    endHour: 15,
    isComingSoon: false,
  },
  {
    name: 'Desde la Cantera',
    slug: 'desde-la-cantera',
    logoPath: '/images/programas/desde-la-cantera.png',
    days: ['J'],
    startHour: 19,
    endHour: 20,
    isComingSoon: false,
  },
  {
    name: 'El Rincon del Negro',
    slug: 'el-rincon-del-negro',
    logoPath: '/images/programas/el-rincon-del-negro.png',
    days: ['J'],
    startHour: 14,
    endHour: 15,
    isComingSoon: false,
  },
  {
    name: 'El Sprint',
    slug: 'el-sprint',
    logoPath: '/images/programas/el-sprint.png',
    days: ['V'],
    startHour: 14,
    endHour: 15,
    isComingSoon: false,
  },
  {
    name: 'Level Up',
    slug: 'level-up',
    logoPath: '/images/programas/level-up.png',
    days: [],
    startHour: 0,
    endHour: 0,
    isComingSoon: true,
  },
];

export const DAY_LABELS: Record<string, string> = {
  L: 'Lunes',
  M: 'Martes',
  X: 'Miercoles',
  J: 'Jueves',
  V: 'Viernes',
};

export const DAY_SHORT: Record<string, string> = {
  L: 'L',
  M: 'M',
  X: 'X',
  J: 'J',
  V: 'V',
};
